### ISSUE TITLE
EIP-1559 update for verifyPOW using ethash to process modified header with baseFeePerGas

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/horizon#25]
for any blocks after the London hard fork that introduced eip 1559, the ethash validation fails: https://github.com/harmony-one/horizon/blob/main/tools/eth2hmy-relay/lib/DagProof.js#L59. this probably needs some adjustment in the ethash library https://github.com/harmony-one/horizon/tree/main/tools/eth2hmy-relay/ethash/dist

**Comment by peekpi** [comment]
EIP1559 appended the `base_fee_per_gas` field into the block header, so the library computes the wrong block hash and then fails validation.
