### ISSUE TITLE
Merge two different merkle prover code

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/horizon#28]
currently eth prover and hmy prover are using two different merkle library code although the logic is more or less same. get rid of eth side merkle library code and utilize hmy side one and pull it out into libs/

1) https://github.com/harmony-one/horizon/blob/main/contracts/EthereumProver.sol
2) https://github.com/harmony-one/horizon/blob/main/contracts/lib/MPT.sol

there is also another more efficient library exists, which can be utilized "@layerzerolabs/proof-evm/contracts/ILayerZeroValidationLibrary.sol";

**Comment by peekpi** [comment]
seem like the proof data formats of harmony side one are different with eth side one. is there any script that can generate the proof data from eth node?
